### PR TITLE
Fix issue #416 and google-java jar added

### PR DESCRIPTION
**Pull request by aionick**

### CODE REVIEW

**Comment by qoire** [comment]
Is there any internal reference a user can use to setup the linting/formatting process?

**Comment by aionick** [comment]
The pre-commit file should be moved into the user's local .git/hook directory. The .git directory is local only so I've stored this file in .gitsettings for now

**Comment by yulongaion** [comment]
Can we integrate the formatting thing into ant, e.g. `ant format`, so we can check code style any time?

**Comment by AionJayT** [comment]
@yulongaion good idea, how about creating a ticket for add ant format task, then we do another PR?

**Pull request merged**
